In [37]:
import numpy as np
import pandas as pd
import datetime

In [38]:
capston_df = pd.read_csv('dataset/rawdata/Sales_Dataset.csv')
capston_df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Order Date,CustomerName,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [39]:
capston_df.columns

Index(['Order ID', 'Amount', 'Profit', 'Quantity', 'Category', 'Sub-Category',
       'PaymentMode', 'Order Date', 'CustomerName', 'State', 'City',
       'Year-Month'],
      dtype='object')

In [40]:
capston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      1194 non-null   object
 1   Amount        1194 non-null   int64
 2   Profit        1194 non-null   int64
 3   Quantity      1194 non-null   int64
 4   Category      1194 non-null   object
 5   Sub-Category  1194 non-null   object
 6   PaymentMode   1194 non-null   object
 7   Order Date    1194 non-null   object
 8   CustomerName  1194 non-null   object
 9   State         1194 non-null   object
 10  City          1194 non-null   object
 11  Year-Month    1194 non-null   object
dtypes: int64(3), object(9)
memory usage: 112.1+ KB

In [41]:
# Standardise the columns
capston_df.columns = (
    capston_df.columns.str.strip()
    .str.lower()
    .str.replace(' ', '_', regex=True)
    .str.replace('-', '_', regex=True)
)
capston_df.head()

,order_id,amount,profit,quantity,category,sub_category,paymentmode,order_date,customername,state,city,year_month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [42]:
# Check for duplicate row
# capston_df.duplicated().any() 
# capston_df.duplicated().sum() # Count how many duplicate
# capston_df[capston_df.duplicated()] # Display DUplicated rows

### Normalising the data (Building Dimensional Tables)

In [43]:
# customer table
customer_df = capston_df[['customername', 'city', 'state']].drop_duplicates().reset_index(drop=True)
customer_df['customer_id'] = customer_df.index + 1
customer_df = customer_df[['customer_id', 'customername', 'city', 'state']]

customer_df

     customer_id        customername           city     state
0              1       David Padilla          Miami   Florida
1              2       Connor Morgan        Chicago  Illinois
2              3        Robert Stone        Buffalo  New York
3              4         John Fields        Orlando   Florida
4              5       Clayton Smith          Miami   Florida
..           ...                 ...            ...       ...
802          803        Megan Mclean  New York City  New York
803          804        Caitlin Hunt      Rochester  New York
804          805       Jenna Holland         Austin     Texas
805          806  Stephanie Oconnell        Buffalo  New York
806          807         Andrea Hill        Chicago  Illinois

[807 rows x 4 columns]

In [44]:
# payment_df method table
payment_df = capston_df[['paymentmode']].drop_duplicates().reset_index(drop=True)
payment_df['payment_id'] = payment_df.index + 1
payment_df = payment_df[['payment_id', 'paymentmode']]

payment_df

   payment_id  paymentmode
0           1          UPI
1           2   Debit Card
2           3          EMI
3           4  Credit Card
4           5          COD

In [45]:
# product_df table

product_df = capston_df[['category', 'sub_category']].drop_duplicates().reset_index(drop=True)
product_df['product_id'] = product_df.index + 1
product_df = product_df[['product_id', 'category', 'sub_category']]

product_df

    product_id         category      sub_category
0            1      Electronics  Electronic Games
1            2      Electronics          Printers
2            3  Office Supplies              Pens
3            4      Electronics           Laptops
4            5        Furniture            Tables
5            6        Furniture            Chairs
6            7  Office Supplies           Markers
7            8        Furniture             Sofas
8            9  Office Supplies             Paper
9           10  Office Supplies           Binders
10          11      Electronics            Phones
11          12        Furniture         Bookcases

In [46]:
# Convert to Date Format
# capston_df['order_date'] = pd.to_datetime(capston_df['order_date'], format='mixed') # formatting datatype of order_date column to datetime 

# capston_df['year'] = capston_df['order_date'].dt.year
# capston_df['month'] = capston_df['order_date'].dt.month
# capston_df['day'] = capston_df['order_date'].dt.day

# # date_df table
# date_df = capston_df[['order_date', 'year_month', 'year', 'month', 'day']].reset_index(drop=True)
# date_df['date_id'] = date_df.index + 1
# date_df = date_df[['date_id', 'order_date', 'year', 'month', 'day']]

# date_df

In [49]:
order_fact_df = capston_df[['order_id', 'amount', 'profit', 'quantity', 'order_date']].drop_duplicates().reset_index(drop=True)


order_fact_df['order_id'] = order_fact_df.index + 1

order_fact_df['product_id'] = np.random.choice(product_df['product_id'], size=len(order_fact_df))
order_fact_df['customer_id'] = np.random.choice(customer_df['customer_id'], size=len(order_fact_df))
order_fact_df['payment_id'] = np.random.choice(payment_df['payment_id'], size=len(order_fact_df))

order_fact_df['amount'] = order_fact_df['amount'].round(2)
order_fact_df['profit'] = order_fact_df['profit'].round(2)

order_fact_df['order_date'] = pd.to_datetime(order_fact_df['order_date'])
order_fact_df['year'] = order_fact_df['order_date'].dt.year
order_fact_df['month'] = order_fact_df['order_date'].dt.month_name()
order_fact_df['day'] = order_fact_df['order_date'].dt.day


order_fact_df = order_fact_df[['order_id', 'amount', 'profit', 'quantity', 'order_date', 'product_id', 'customer_id', 'payment_id', 'year', 'month', 'day']]

order_fact_df

,order_id,amount,profit,quantity,order_date,product_id,customer_id,payment_id,year,month,day
0,1,9726,1275,5,2023-06-27,10,573,5,2023,June,27
1,2,9726,1275,5,2024-12-27,10,438,4,2024,December,27
2,3,9726,1275,5,2021-07-25,5,237,3,2021,July,25
3,4,4975,1330,14,2023-06-27,10,773,2,2023,June,27
4,5,4975,1330,14,2024-12-27,9,46,1,2024,December,27
...,...,...,...,...,...,...,...,...,...,...,...
1189,1190,8825,3594,15,2024-07-31,2,293,3,2024,July,31
1190,1191,2082,642,8,2020-06-02,1,723,2,2020,June,2
1191,1192,2082,642,8,2022-12-15,6,755,4,2022,December,15
1192,1193,2082,642,8,2020-08-07,11,103,2,2020,August,7
1193,1194,914,163,13,2024-10-26,9,665,5,2024,October,26

In [ ]:
# Check if duplicates exist
order_fact_df.duplicated().sum()

0

In [ ]:
# Compare with original data
print("Original capston_df:", len(capston_df))
print("Order Fact Table:", len(order_fact_df))

Original capston_df: 1194
Order Fact Table: 1194

### Data insertion (to_sql() via SQLAlchemy)

In [ ]:
# Database connection
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

uid = 'postgres'
pwd = 'password'
server = 'localhost'
database = 'capstone'

engine = create_engine(f'postgresql://{uid}:{pwd}@{server}:5432/{database}')

In [ ]:
# Writing Pandas Table into SQL Database
order_fact_df.to_sql("orders_fact", engine, if_exists='replace', index=False)
product_df.to_sql("product_category", engine, if_exists='replace', index=False)
customer_df.to_sql("customers", engine, if_exists='replace', index=False)
payment_df.to_sql("payment_df", engine, if_exists='replace', index=False)

5

### Save data to csv file

In [ ]:
payment_df.to_csv(r'dataset/cleaneddata/payment.csv')
customer_df.to_csv(r'dataset/cleaneddata/customers.csv')
customer_df.to_csv(r'dataset/cleaneddata/product_category.csv')
order_fact_df.to_csv(r'dataset/cleaneddata/orders_fact.csv')